apiVersion: v1
kind: Service
metadata:
        name: httpserver-service
        labels:
                app: httpserver
spec:
        selector:
                app: httpserver
        ports:
        - name: httpserver-port
          protocol: TCP
          port: 8080
          nodePort: 30080
          targetPort: 8080
        type: NodePort
